[keyboard]
bindings = [
    { key = "Enter", mods = "Command", action="ToggleSimpleFullscreen" },
    { key = "v", mods = "Alt", action = "ToggleViMode" },
    { key = "l", mods = "Alt", chars = "\u001BF" },
    { key = "h", mods = "Alt", chars = "\u001BB" },
    { key = "k", mods = "Alt", action = "ScrollLineUp" },
    { key = "j", mods = "Alt", action = "ScrollLineDown" },
    { key = "k", mods = "Shift|Alt", action = "ScrollPageUp" },
    { key = "j", mods = "Shift|Alt", action = "ScrollPageDown" }
]
